### ISSUE TITLE
Can't exclude a type

### ISSUE THREAD

**Issue by dubiousdavid** [greglook/whidbey#18]
I can't seem to get rid of the exception below, even after adding `'datomic.btset.BTSet` to the exclude set.

```clojure
{:exclude-types #{'datomic.db.DB 'datomic.btset.BTSet} ...}
```
```shell
RuntimeException Unable to convert: class datomic.btset.BTSet to Object[]
	clojure.lang.Util.runtimeException (Util.java:221)
	clojure.lang.RT.toArray (RT.java:1583)
	clojure.core/to-array (core.clj:333)
	clojure.core/sort (core.clj:2828)
	clojure.core/apply (core.clj:626)
	clojure.core/partial/fn--4228 (core.clj:2468)
	puget.printer/order-collection (printer.clj:163)
	puget.printer/eval4615/fn--4616 (printer.clj:315)
	clojure.lang.MultiFn.invoke (MultiFn.java:227)
	puget.printer/format-entry (printer.clj:279)
	clojure.core/map/fn--4245 (core.clj:2559)
	clojure.lang.LazySeq.sval (LazySeq.java:40)
```

**Comment by greglook** [comment]
Hmm, I'll take a look. I'm working with Datomic on a new project, so hopefully I'll be able to flush out some of these bugs through direct experience.

**Comment by greglook** [comment]
Which version of whidbey are you using?

**Comment by greglook** [comment]
Turns out this was a documentation issue - the correct key is [`:escape-types`](https://github.com/greglook/puget/blob/f830588bf0eacfc7409595da0f28fe1db82ea1ea/src/puget/printer.clj#L53), not `:exclude-types`. I'll fix the README.
