### ISSUE TITLE
whidbey 1.0.0 doesn't work for me.

### ISSUE THREAD

**Issue by dubiousdavid** [greglook/whidbey#19]
I'm not getting any color or pretty printing when upgrading from [mvxcvi/whidbey "0.6.0"] to [mvxcvi/whidbey "1.0.0"].

**Comment by greglook** [comment]
I'm going to need a few more details. What version of Clojure and Leiningen are you using, and how are you including Whidbey?

**Comment by dubiousdavid** [comment]
Clojure 1.6
Leiningen 2.5.1
~/.lein/profiles.clj :repl profile, :plugins vector

**Comment by greglook** [comment]
Can you try it with the plugin in your `user` profile? Whidbey uses profile-level metadata now to tell Leiningen to load it for the repl task, so you should be able to just stick it in a general profile.

**Comment by dubiousdavid** [comment]
That fixed the issue.
