### ISSUE TITLE
Migrate org.clojure/tools.nrepl 0.2.12 to nrepl 0.5.3

### ISSUE THREAD

**Issue by venantius** [greglook/whidbey#26]
Hiyo - 

Per venantius/ultra#95, clojure.tools.nrepl is dead and has been moved to nrepl/nrepl. 

> Refer to https://metaredux.com/posts/2018/10/29/nrepl-redux.html for more details. All projects should adopt the new package, as the main tooling already switched to it and tools like CIDER will just drop support for the old package very soon.
> 
> That's a simply way of supporting both versions https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl.clj#L11

I'm migrating Ultra upstream but you'll want to update Whidbey as well. The code snippet included above is an effective drop-in choice for now that doesn't require too much thinking.

**Comment by bbatsov** [comment]
@greglook already contributed to the development of nREPL recently, so he knows what to do. I'm assuming that whidbey doesn't need its custom middleware at all, now that it can simply pass the `:printer` option to the nREPL `:eval` op.

**Comment by greglook** [comment]
Thanks y'all, I'll tackle this over the weekend.

**Comment by greglook** [comment]
I upgraded to leiningen 2.8.3 and 6f33e98e3044aaccb950f76006fbd843ec87a7e9 seems to do the trick with the new nREPL code. Nice to not need the `pr-values` substitution hax anymore! I'll do a bit more testing and release 2.0.0 soon.

**Comment by bbatsov** [comment]
Nice!

**Comment by greglook** [comment]
Released 2.0.0 with the updated nREPL dependency code.
