### ISSUE TITLE
Error loading lein repl

### ISSUE THREAD

**Issue by erez-rabih** [greglook/whidbey#31]
I'm getting this error trying to run `lein repl`
```
Error loading clojure.tools.nrepl.middleware.render-values: 
Could not locate clojure/tools/nrepl/middleware/render_values__init.class, clojure/tools/nrepl/middleware/render_values.clj or clojure/tools/nrepl/middleware/render_values.cljc on classpath. 
Please check that namespaces with dashes use underscores in the Clojure file name.
```
I'm using `[mvxcvi/whidbey "2.1.1"]` on my ~/.lein/profiles.clj
clojure version 1.10.1
lein version 2.9.1

**Comment by greglook** [comment]
That's extremely odd - `clojure.tools.nrepl` namespaces are from the older clojure-contrib version of nREPL and aren't used by modern versions of whidbey or leiningen. Can you run `lein deps :plugin-tree` and ensure that you're actually getting version 2.1.1 on your classpath?

**Comment by erez-rabih** [comment]
I resolved the issue
It seems that it had a conflict with lein cloverage (https://github.com/cloverage/cloverage) v 1.0.13

Once I updated the cloverage plugin to 1.1.1 I could successfully run the repl
Tracking that was a bit hard because I had hard time finding the source that required the missing namespace

**Comment by greglook** [comment]
Glad it's working for you. :+1:
