### ISSUE TITLE
trampoline repl fails

### ISSUE THREAD

**Issue by trptcolin** [greglook/whidbey#6]
I'm having some trouble tracking down why this is exactly, but `lein trampoline repl` will work without whidbey, but not with it. I tracked it down to the following request/reply sequence, but I'm not sure how this is happening:

``` clojure
# Both of these use pr-str
request: {:id "84c93587-7b69-4f2e-8664-28945c839272", :code "(clojure.core/binding [clojure.core/*ns* (clojure.core/symbol \"reply.eval-modes.nrepl\")] (set! *print-length* nil))", :op "eval"}
response: {:id "84c93587-7b69-4f2e-8664-28945c839272", :ns "user", :session "f10af298-3a82-4351-8d24-c6d537d9e838", :value []}
```

Note: the value is `[]` instead of `"nil"` or even `"[]"`, so REPLy's `read-string` call fails on it. I actually haven't done much w/ nREPL middleware, but I'm wondering if somehow whidbey only gets partially installed or something under `lein trampoline`. Any ideas?

**Comment by cemerick** [comment]
NREPL-53 is fixed as of `[org.clojure/tools.nrepl "0.2.7"]`, so maybe @gfredericks' patch resolves this?

**Comment by greglook** [comment]
Thanks for the heads up @cemerick, I'll test it out!

**Comment by gfredericks** [comment]
Related: https://github.com/technomancy/leiningen/issues/1829

**Comment by greglook** [comment]
Hey, this started working at some point!
